name: Android CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build dropped with Gradle
      run: ./gradlew build -p droppedapk
#    - name: Replace droppedapk with new one
#      run: yes | cp -f "droppedapk/build/outputs/apk/debug/app-debug.apk" tests/
    - name: Build app with Gradle
      run: ./gradlew build -p app
    - name: Upload release
      uses: actions/upload-artifact@v4
      with:
        path: |
          app/build/outputs/apk/debug
          droppedapk/build/outputs/apk/release
